version: '3.9'

services:
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_pipeline_test
    ports:
      - '5433:5432'
    volumes:
      - ./src/db/migrations/0001_initial.sql:/docker-entrypoint-initdb.d/0001_initial.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
